name: frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  tap_debouncer: ^2.2.0
  shared_preferences: ^2.3.2
  get_it: ^8.0.2
  intl: ^0.19.0
  pdf: ^3.11.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  printing: ^5.13.4
  syncfusion_flutter_charts: ^27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
