/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_unibuc_find_my_path_career_test_CareerTestJNI */

#ifndef _Included_com_unibuc_find_my_path_career_test_CareerTestJNI
#define _Included_com_unibuc_find_my_path_career_test_CareerTestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unibuc_find_my_path_career_test_CareerTestJNI
 * Method:    loadCareerTestResults
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unibuc_find_1my_1path_career_1test_CareerTestJNI_loadCareerTestResults
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
